### ISSUE TITLE
Using --createDatasetCol

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/projectgenerator#101]
And while digitizing, a user needs to be able to choose on which dataset he wants to work.

**Comment by pramisters** [comment]
this option requires the option --dataset (see documentation of ili2pg)

**Comment by m-kuhn** [comment]
@zigertiger based on the document you wrote about baskets, the user needs to choose the basket to work on, not the dataset, correct?

> Die ili2pg-Option --createDatasetCol führt redundante Informationen ein und ist nicht erforderlich!

**Comment by pramisters** [comment]
This option was mainly for KKGEO.

> Erstellt in jeder Tabelle eine zusätzlich Spalte T_datasetname mit dem Namen/Identifikator des Datensatzes. Die Option bedingt die Option --dataset. Die Spalte ist redundant zur Spalte datasetname der Tabelle t_ili2db_dataset (siehe Kapitel Abbildungsregeln/Metadaten).
