### ISSUE TITLE
No conection to docker postgis database. 

### ISSUE THREAD

**Issue by juusechec** [opengisch/projectgenerator#104]
Hello. I'm running the test command `docker-compose -f .docker/docker-compose.travis.yml run qgis /usr/src/.docker/run-docker-tests.sh` and I'm get a problem with network configuration in Docker Compose file. Executing this, it shows the message:

```
org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "172.22.0.3", user "docker", database "gis", SSL off

    ch.ehi.ili2db.base.Ili2db.runSchemaImport(Ili2db.java:927)
    ch.ehi.ili2db.base.Ili2db.run(Ili2db.java:203)

    ch.ehi.ili2db.AbstractMain.domain(AbstractMain.java:433)

    ch.ehi.ili2pg.PgMain.main(PgMain.java:70)
  FATAL: no pg_hba.conf entry for host "172.22.0.3", user "docker", database "gis", SSL off
```

This is because the containers ***postgres*** is not in same subnet that is specify for ***qgis*** in `.docker/docker-compose.travis.yml`.

The solution to this was changing `- ALLOW_IP_RANGE="172.18.0.0/16"` by `- ALLOW_IP_RANGE="172.0.0.0/8"`. What is the reason for this exactly subnet (172.18.0.0/16)?

Thanks a lot!

**Comment by m-kuhn** [comment]
This was just copied from somewhere else, the change looks safe to me. Can you make a pull request?

CC @3nids
