### ISSUE TITLE
ili2pg-Command in plain text

### ISSUE THREAD

**Issue by zigertiger** [opengisch/projectgenerator#110]
Complete ili2pg-Command ist shown in the projectgenerator log in plain text. This is an issue since this shows also the user's password.
![progen-ili2pg-log](https://user-images.githubusercontent.com/25387992/30731144-e20b2cba-9f6b-11e7-98ad-4fa9f9725ac1.PNG)

**Comment by gacarrillor** [comment]
Closed by PR #112.
