### ISSUE TITLE
CREATE EXTENSION IF NOT EXISTS "uuid-ossp"

### ISSUE THREAD

**Issue by zigertiger** [opengisch/projectgenerator#111]
This was also an issue with other QGIS plugins since we already have a uuid function in PostgreSQL... The projectgenerator's log throws

`  ERROR: function "uuid_generate_v4" already exists with same argument types `

And thus, the data model cannot be configured. [ Finished(1) ]

**Comment by m-kuhn** [comment]
Local issue, probably caused by an existing installation of `uuid_generate_v4` in an unsupported way.
