### ISSUE TITLE
Relations for tables with several geometry fields

### ISSUE THREAD

**Issue by gacarrillor** [opengisch/projectgenerator#116]
Relations are not being propagated to layers with multiple geometry attributes when loaded to QGIS.

For instance, the `KbS_LV95_V1_3` model from INTERLIS repositories has the `Belasteter_Standort` class with point and polygon geometries. QGIS loads the PostgreSQL table `belasteter standort` as 2 layers (one per geometry type) called equally but only the one with the point geometry gets the relations.

@m-kuhn, I think this a QGIS issue.

**Comment by gacarrillor** [comment]
As agreed with @m-kuhn , this issue is still unsolved. Reopening.

**Comment by m-kuhn** [comment]
To be precise, it's still missing for attributes like `statusAltlV`.
It's partially resolved, tabs and embedded forms for `parzellenidentifikation` etc. are now shown.
