### ISSUE TITLE
Multiple vertices at the same position kills ili2pg export

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/projectgenerator#123]
Ili2db doesn't export when there are multiple vertices at the same position.

When tracing arcs vertices result in higher frequency / closer to each other than allowed by Interlis precision specifications and are then (probably) snapped to the same position by ili2db at export time before the check.

* Fix in ili2db (drop additional vertices, @claeis does this sound like a feasible approach?)
* Less precision while digitizing in QGIS. How do we get the allowed precision from the model inside QGIS?

**Comment by claeis** [comment]
Any user/client of the data should see the same data. Therefore any export (incl. ili2pg) must not modify the data.

**Comment by m-kuhn** [comment]
> any export (incl. ili2pg) must not modify the data

Does that mean that no snapping (or precision truncating) occurs when ili2db does an export? In this case our base assumption (first comment) was wrong already.

**Comment by claeis** [comment]
Depending on the format, some truncation is done, but only in the sense of a last resort; to avoid too many errors. It is better to do it before the export. This also gives control over how it is done.

**Comment by m-kuhn** [comment]
Information about precision should be available in `t_ili2db_column_prop`.

Remaining task: implement precision/snap_to_grid flags for layers in QGIS. Use this configuration option (at least) when tracing. Set the project layer configuration based on the Interlis specification.
