### ISSUE TITLE
New default option --importTid

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/projectgenerator#127]
`--importTid`

**Comment by m-kuhn** [comment]
@pramisters @zigertiger, not sure who proposed this option, is this for schemaimport or import?

**Comment by pramisters** [comment]
This is for schemaimport. Should not hurt anybody as it's just an additional column that will be automatically filled with the Transfer ID when importing data. But it's very helpful vor debugging/analysing.

**Comment by romefi** [comment]
It's needed for import (if data is edited/collected) and schemaimport.

**Comment by pramisters** [comment]
Are you sure?
The option itself (--importTID) is only needed when the schema is created, not for the import command if the column t_ili_tid already exists.

**Comment by romefi** [comment]
You can import data without generating schema first. That way the schema is generated by the import statement. In that case you need the --importTID there, if the schema don't exist yet.

**Comment by m-kuhn** [comment]
So far, the configuration was set to show an `t_ili_tid` attribute in the form as read-only where present.
I cannot recall the reason for this decision right now.
Since now `t_ili_tid` is on every table, the logical step would be to hide it from the form (I think, so far no-one missed it on the form) but since it's explicitly listed as a "read-only by default column" in the sourcecode I am a bit hesitant to hide it.
Opinions?

**Comment by pramisters** [comment]
It can be hidden by default as it holds no useful information for the "normal" user that edits data.
