### ISSUE TITLE
Additional metaattributes

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/projectgenerator#128]
For some use cases it would be nice to have additional meta attributes

* Display String / Identifier
* Form style (two lists vs. embedded form)...
* Widget hints

It would be nice to have a list of all meta attributes in the database

**Comment by m-kuhn** [comment]
https://github.com/claeis/ili2db/issues/140

**Comment by romefi** [comment]
Reminder from workshop:
If a layer should be classified by a specific attribute and values from a known picklist, the attribute should be defined as metainfo and the layer in QGIS classified after the values of the picklist. ie: baulinie has attribute "status" with picklist values "gültig, offen, gelöscht". The layer baulinie should be classified by attribute status and have the subentries "gültig, offen, gelöscht".

**Comment by m-kuhn** [comment]
https://github.com/opengisch/projectgenerator/issues/132

**Comment by m-kuhn** [comment]
Available in https://github.com/claeis/ili2db/releases/tag/ili2pg-3.11.2

https://github.com/claeis/ili2db/pull/147
https://github.com/claeis/ili2db/pull/149
