### ISSUE TITLE
referenced objects not via t_id (FK)

### ISSUE THREAD

**Issue by zigertiger** [opengisch/projectgenerator#135]
maybe already in the pipeline...

object referencing is established by choosing t_id (FK) which is not feasible. referenced objects should be referencable via defined field values of the referenced table (e.g. type names).

![referenced-objects](https://user-images.githubusercontent.com/25387992/34865371-bf5a0c12-f778-11e7-81fc-8194f3fa85b7.png)

**Comment by m-kuhn** [comment]
Depends on https://github.com/opengisch/projectgenerator/issues/128

**Comment by signedav** [comment]
It's about to load the meta attribute for the display expression defined in the interlis file (expl. https://github.com/opengisch/projectgenerator/blob/master/projectgenerator/tests/testdata/ilimodels/ExceptionalLoadsRoute_V1.ili)
```
!!@ dispExpression="TypeOfRoute"
CLASS ...
```
This would be written into an ili2db table, where the projectgenerator form-part can read it from.

**Note to myself:**
To have the project select in the projectgenerator the Model `ExceptionalLoadsRoute_LV95_V1` and import the Interlis Transfer Files `/home/david/doc/clients/SH/ExceptionalLoadsRoute_Catalogue_V1.xml`

**Comment by m-kuhn** [comment]
> This would be written into an ili2db table, where the projectgenerator form-part can read it from.

Not exactly this one, it's another ili2db meta table

**Comment by signedav** [comment]
`t_ili2db_meta_attr`

**Comment by signedav** [comment]
Done with PR #189
