### ISSUE TITLE
Integer range widget minimum value with NULL

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/projectgenerator#141]
When an integer range widget allows NULL values, it's not possible to insert the minimum value (e.g. 0-100 > doesn't allow writing 0, it will be replaced by NULL)

**Comment by m-kuhn** [comment]
Fixed upstream

**Comment by gacarrillor** [comment]
In Project Generator 3.2.3, for a model like this: 

```
INTERLIS 2.3;
MODEL test_ranges (es)
AT "mailto:user@localhost"
VERSION "2017-08-01"  =
  TOPIC Catastro =
    CLASS Avaluo =
      Numero_Pisos : MANDATORY 1 .. 100;
    END Avaluo;
  END Catastro;
END test_ranges.
```

The range widget doesn't allow users to enter the minimum value `1`.

**Comment by m-kuhn** [comment]
Which QGIS version?

**Comment by gacarrillor** [comment]
Just added more details.

**Comment by gacarrillor** [comment]
> Or are you sure this is related to the project generator version?

Nope, just added the version to give more information and make the issue easier to replicate. (That's how I'd like to read issues :) )

**Comment by gacarrillor** [comment]
Solved by @m-kuhn in https://github.com/qgis/QGIS/pull/7354
