### ISSUE TITLE
DateTime widget issue with current date

### ISSUE THREAD

**Issue by gacarrillor** [opengisch/projectgenerator#145]
You can download test models from [test_model.zip](https://github.com/opengisch/projectgenerator/files/1772514/test_model.zip) The gif at https://issues.qgis.org/issues/18299 uses model _CIAF_LADM_, table _persona_.

**Comment by m-kuhn** [comment]
![Demo of issue](https://issues.qgis.org/attachments/download/12315/date_time_widget.gif)

**Comment by 3nids** [comment]
https://github.com/qgis/QGIS/pull/6548
and
https://github.com/qgis/QGIS/pull/6550

**Comment by gacarrillor** [comment]
Solved by @3nids in https://github.com/qgis/QGIS/pull/6548
