### ISSUE TITLE
multiple model versions

### ISSUE THREAD

**Issue by zigertiger** [opengisch/projectgenerator#151]
SITUATION:
There can be multiple versions of a data model with the same model name. Obsolete model(file)s are stored in the "obsolete/" directory of models.geo.admin.ch but remain listed in ilimodels.xml. Each model has a name and a version date that is stored in ilimodels.xml

Example: 
[1 - obsolete model version]
   name: Laermempfindlichkeitsstufen_LV95_V1_1
   file: obsolete/Laermempfindlichkeitsstufen_LV03_V1_1_o0.ili
   version: 2017-02-16

[2 - actual model version]
   name: Laermempfindlichkeitsstufen_LV95_V1_1
   file: BAFU/Laermempfindlichkeitsstufen_V1_1.ili
   version: 2018-02-16
   precursorVersion: 2017-02-16

PROBLEM:
The projectgenerator apparently handles only model names but not versions. When I choose the given model to be implemented, I get two models listed (attachment).

SOLUTION:
The projectgenerator shall evaluate model names and versions as well. Possible extension: the projectgenerator filters obsolete model version.
At least, model name AND version shall be listed in the models field of the gui dialog.

![models](https://user-images.githubusercontent.com/25387992/37196866-bf5ef2aa-2378-11e8-89eb-5a65a64e6076.png)

**Comment by zigertiger** [comment]
I'll check that with Claude Eisenhut (what ili2pg is actually doing with precursor model versions).

**Comment by m-kuhn** [comment]
@zigertiger do we have an update on this?

**Comment by zigertiger** [comment]
just asked Claude via E-Mail

**Comment by claeis** [comment]
Only one ili file is current. 

The ``precursorVersion`` element from ilimodels.xml entries must be used to build an ordered list of models with the same name to know which one is the current.

**Comment by m-kuhn** [comment]
Does this mean only the current version can be loaded with ili2db and listing any other version in a gui is not meaningful?

**Comment by claeis** [comment]
Yes, only the current version can be loaded. (Would it not be better, if the projectgenerator uses the existing code (in ili2c.jar) to read the (current) model list from the repositories?)

**Comment by claeis** [comment]
``--help,...but the option --listModels that provides the functionality to the user  is not yet there (claeis/ili2c#15)

**Comment by m-kuhn** [comment]
It would be nice from a perspective, that all code is in a single place.
On the other hand it will pose some restrictions - or at least complicate things - when it comes to error handling and require parsing information from stdout, which is another point of failure. And it might reduce the responsive GUI we have now, it's used in an autocompleter which is supposed to open immediately. Currently we fill the list incrementally when available (and therefore are unaffected by timeouts on repos which are down).

**Comment by claeis** [comment]
While implementing claeis/ili2c#15, I discovered that some models are in more than one repository. Which is wrong.
