### ISSUE TITLE
Add --coalesceMultiPoint --coalesceArray

### ISSUE THREAD

**Issue by pramisters** [opengisch/projectgenerator#159]
New, important Options since 3.11.0

**Add --coalesceMultiPoint --coalesceArray**

**Comment by m-kuhn** [comment]
For now, this is not a quick fix unfortunately.

ili2gpkg is still in version 3.10.5 (http://www.eisenhutinformatik.ch/interlis/ili2gpkg/) which does not support `coalesceMultiPoint`. We either need to have separate options for ili2gpkg and ili2pg or wait for a new release of ili2gpkg.

**Comment by pramisters** [comment]
There's a new ili2gpkg/ili2pg release (both 3.11.3): http://www.eisenhutinformatik.ch/interlis/ili2gpkg/
After a test I can confirm that ili2gpkg defines the geometry type MULTIPOINT if the corresponding metaattribute is present in the ili-model.

@m-kuhn : Could you update the projectgenerator to 3.11.3 both for ili2pg and ili2gpkg?

What is not clear to me is how ili2gpkg is representing an array since native array data types don't exist in SQLite/GeoPackage.
