### ISSUE TITLE
Error generating model PlanerischerGewaesserschutz_V1

### ISSUE THREAD

**Issue by romefi** [opengisch/projectgenerator#16]
Model: http://models.geo.admin.ch/BAFU/PlanerischerGewaesserschutz_V1.ili

Errormessage appended
![error_import_planerischergewaesserschutz_v1](https://cloud.githubusercontent.com/assets/26796989/24512469/f3ec770e-156e-11e7-9cb4-b959f415eedb.JPG)

**Comment by romefi** [comment]
Just noticed this error only appears, if there is already an schema being generatet with projectgenerator before. I imported http://models.geo.admin.ch/BAFU/KbS_V1_3.ili first, then http://models.geo.admin.ch/BAFU/PlanerischerGewaesserschutz_V1.ili. If I import http://models.geo.admin.ch/BAFU/PlanerischerGewaesserschutz_V1.ili in an empty db, all works fine.

**Comment by m-kuhn** [comment]
Should be fixed
