### ISSUE TITLE
Bag of Enums

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/projectgenerator#171]
Should be displayed as lists where multiple entries can be selected/checked.
To decide: relation reference or value relation.

**Comment by pramisters** [comment]
Suggestion:
If the ENUM attribute is listed in t_ili2db_meta_attrs (with attr_value = ARRAY) use "value relation" widget (and "allow multiple selections") instead of "list" widget.

**Comment by m-kuhn** [comment]
sounds good, I'm currently working an a new offer that includes this

**Comment by m-kuhn** [comment]
as far as I can tell, the only information currently available is that it is an ARRAY, the information that it is a foreign key and especially which other table is involved is not available in the database. Looking into this, hints welcome.

**Comment by gacarrillor** [comment]
We can use the custom parser we have (to discover domains) for this use case as well. Perhaps we can work on this when you are in our country.

**Comment by m-kuhn** [comment]
I was just looking into that, as a temporary workaround, that's not a bad idea. We'll clarify about this on the meeting tomorrow. :+1:

**Comment by pramisters** [comment]
One point to remember is the fact that in INTERLIS 2.3 the BAG OF construct needs a STRUCTURE object as an intermediate object before it can refer to a datatype.

Just an example out of the model:
[ZG_Naturschutz_und_Erholungsinfrastruktur_V1.txt](https://github.com/opengisch/projectgenerator/files/2123542/ZG_Naturschutz_und_Erholungsinfrastruktur_V1.txt)


```
CLASS Erholungsinfrastruktur_Punktobjekt EXTENDS Punktobjekt =   
  !!@ili2db.mapping=ARRAY   
  Typ: BAG {1..*} OF EI_Punkt_Typ;   

```

**Comment by pramisters** [comment]
One point to remember is the fact that in INTERLIS 2.3 the BAG OF construct needs a STRUCTURE object as an intermediate object before it can refer to a datatype.

Just an example out of the model:
[ZG_Naturschutz_und_Erholungsinfrastruktur_V1.txt](https://github.com/opengisch/projectgenerator/files/2123542/ZG_Naturschutz_und_Erholungsinfrastruktur_V1.txt)

```
CLASS Erholungsinfrastruktur_Punktobjekt EXTENDS Punktobjekt = 
  !!@ili2db.mapping=ARRAY
  Typ: BAG {1..*} OF EI_Punkt_Typ;

```
