### ISSUE TITLE
Project Generator v3.0.6 freezes loading relations for tables with more than one geometry column

### ISSUE THREAD

**Issue by gacarrillor** [opengisch/projectgenerator#178]
v3.0.5 works fine.

The problem we face is with `Terreno` table (it has polygon and point geometries) from the LADM_COL [Catastro_Registro_Nucleo](https://github.com/AgenciaImplementacion/LADM_COL/tree/master/Catastro_Multiproposito) model.

**Comment by m-kuhn** [comment]
Freezes while generating or while opening the form?

3.0.6 was especially released for multi-geometry tables, with the KbS model it works for me.

**Comment by gacarrillor** [comment]
When running a Generate from PostGIS, the interface freezes at [90%](https://github.com/opengisch/projectgenerator/blob/master/projectgenerator/gui/generate_project.py#L285).

**Comment by juusechec** [comment]
Same here
![screenshot from 2018-04-19 15-02-39](https://user-images.githubusercontent.com/4140058/39015380-db6d2dec-43e2-11e8-884f-291ef4575604.png)
