### ISSUE TITLE
Grouping legend entries (to be disussed)

### ISSUE THREAD

**Issue by romefi** [opengisch/projectgenerator#18]
There are many legend entries generated, which doesn't really seem necessary for the project or at least not that important, even ones with geometry. Maybe there is a possibility to do an automatic and clever grouping of the legend entries.

**Comment by m-kuhn** [comment]
This is *slightly* started based on geometries being top-level and tables in a group.

Geometries are also ordered by polygon / line / point (because of rendering)

Any smart idea will be welcome.

**Comment by romefi** [comment]
Sorry, my mistake. Just noticed that if you import a second model in the same db, but with new schema, the project generator gets the legend entries of all other schemas too. That confused me, might be an error.

**Comment by m-kuhn** [comment]
Agreed, we need to discuss what to do with schemas (in the context of ili2pg only the active schema should be imported).

**Comment by romefi** [comment]
Group by geometry, data-group and value list-group (to be defined in ili2pg)

**Comment by m-kuhn** [comment]
> Group by geometry, data-group and value list-group (to be defined in ili2pg)

I guess we can close that, we've got exactly this.
