### ISSUE TITLE
Filtering by schema

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/projectgenerator#20]
When loading directly from Postgis from a schema I noticed that also the table pulic.chenyx06_triangles was loaded (needed by ST_Fineltra())

This table is usually not wanted in the project and should be suppressed.

**Comment by m-kuhn** [comment]
Should this table be blacklisted with the full name or a substring match (regex like `chenyx.*` or so)?

**Comment by andreasneumann** [comment]
To be honest - I have no idea why the table was picked at all. It is in a different schema and as to my knowledge isn't reference at all in the schema I imported.

Any ideas why this table from the public schema was chosen?

Maybe I overlooked some reference.

**Comment by m-kuhn** [comment]
At the moment the schema is only used for the ili2pg import and not for filtering the output definitions.

We could adjust that to filter by the schema if specified. The table itself can still be blacklisted.
