### ISSUE TITLE
Range widget NULL values

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/projectgenerator#201]
1. If "Representation for NULL values" (in Settings/Options/Data Sources) is left emtpy, NULL values are displayed wrongly in the form as [minimum value] - 10E-Precision:
--> `-0.1` instead of an empty field.

------------------
[ZG_Naturschutz_und_Erholungsinfrastruktur_V1.txt](https://github.com/opengisch/projectgenerator/files/2026073/ZG_Naturschutz_und_Erholungsinfrastruktur_V1.txt)

DB:
`CONSTRAINT erhlngsnfrstktr_pnktbjekt_naechste_kontrolle_check CHECK (naechste_kontrolle >= 2018 AND naechste_kontrolle <= 2999)
`

2. If "Representation for NULL values" (in Settings/Options/Data Sources) is left emtpy, NULL values are displayed wrongly in the form as [minimum value] - 10E-Precision:
--> `2017` instead of an empty field.

Might be related to QGIS (https://issues.qgis.org/issues/18583)

**Comment by m-kuhn** [comment]
@pramisters did you test that with 3.0, master or both?

**Comment by pramisters** [comment]
**Master (6165e4c8d6):**
"Representation for NULL values" left empty --> NULL is displayed as 2017 --> wrong!
"Representation for NULL values" = [string], i.e. MYNULL --> NULL is displayed as MYNULL --> correct!

**3.0.3 (8a899c8758):**
"Representation for NULL values" left empty --> NULL is displayed as 2018 --> wrong! AND minimum value only starts at 2019 --> wrong!

"Representation for NULL values" = [string], i.e. MYNULL --> NULL is displayed as MYNULL (correct), but minimum value only starts at 2019 --> wrong!

**Comment by m-kuhn** [comment]
It is definitely a QGIS bug, since it's connected to a very particular setup (empty value for NULL) I wonder how we should best get this fixed

**Comment by pramisters** [comment]
You are the expert ;-)
So, the bug report exists already: https://issues.qgis.org/issues/18583

**Comment by pramisters** [comment]
Confirmed! It works now!
