### ISSUE TITLE
Feature count is wrong

### ISSUE THREAD

**Issue by pramisters** [opengisch/projectgenerator#206]
Layers should be added **without** the parameter "estimatedmetadata=true".

It confuses users a lot if the "Feature Count" displays wrong numbers, i.e. often 0, although tables are not empty.

**Comment by pramisters** [comment]
1. When you define a new PostGIS connection QGIS the default value of estimatedmetadata is FALSE. Why do you  need to change a default behaviour ?
2. The ProjectGenerator is often used with test DBs.

**Comment by m-kuhn** [comment]
Not using estimated metadata leads to a forced iteration over the whole dataset upon every opening of a qgis project which can have very bad performance impacts. Feature counts are something that can be very well cached and monitored db side, so sacrificing performance for it seems like a bad tradeoff. Thus, in general having proper maintenance tools on the DB enabled sounds like the right spot to fix things.

We can add an option for it with a good explanation about the implications to educate the user to make an informed decision.

**Comment by pramisters** [comment]
An option (similar to QGIS itself) is OK for us.

**Comment by romefi** [comment]
Default value is false

**Comment by m-kuhn** [comment]
After thinking about this again, I think we should skip this option and always disable estimated metadata. We can look for a different solution once we run into troubles with big databases (or similar).

**Comment by pramisters** [comment]
That's fine for me :-)
