### ISSUE TITLE
List models as dropdown if ili is loaded

### ISSUE THREAD

**Issue by romefi** [opengisch/projectgenerator#212]

**Comment by signedav** [comment]
Means it should look like when you enter a letter (and the proposed models are in the dropdown), but with all the unfiltered models listed? And when? On tip of the text-line-edit or should it have a dropdown symbol like a combobox?

**Comment by m-kuhn** [comment]
> Means it should look like when you enter a letter (and the proposed models are in the dropdown), but with all the unfiltered models listed?

Exactly

> On tip of the text-line-edit or should it have a dropdown symbol like a combobox?

I think both are fine

**Comment by signedav** [comment]
Hm... When we load an ili-file the model-lineedit is filled with a model. So it's not empty then. 

On click on it, shouldn't it use the existing text? Should popup the dropdown with all the models instead?
Or only when empty?

**Comment by m-kuhn** [comment]
There's some logic in ili2db to choose a default model (last in the file IIRC), the text in there just copies this.

Possibilities I see:
 * ComboBox (so there's a button to dropdown)
 * Set the default model name as placeholder and popup on click on empty
 * Whatever else you can come up with ;P

**Comment by signedav** [comment]
I decided to do it without combo and make an extended LineEdit:

 Before it was like this:
- Click on the Edit -> nothing happens
- Type in a letter -> popup with filtered values
- Delete last letter -> nothing happens

I planned:
- Click on the empty Edit -> popup with all the values if it's empty
- Click on Edit with content -> nothing happens *
- Type in a letter -> popup with filtered values
- Delete last letter -> popup with all the values

\* I'm not sure if it should popup with all the values here as well. I'm not sure if this was the initial request here.

**Comment by signedav** [comment]
I tend not popup unfiltered values if there is a value in it, because this could be confusing with 'similar? values....

**Comment by signedav** [comment]
![select_completion](https://user-images.githubusercontent.com/28384354/45698723-f0751d00-bb68-11e8-904b-0781fd24dae0.gif)
