### ISSUE TITLE
Preserve arcs in Interlis models

### ISSUE THREAD

**Issue by fahuber** [opengisch/projectgenerator#217]
It should be possible to import curved geometries, thus the --strokeArcs argument should be optional (or be removed again). Otherwise, imported (and segmented) arcs cause an error while exporting again.

**Comment by m-kuhn** [comment]
Is the main request here that you need to be able to work with arcs or that there is an export error?

**Comment by fahuber** [comment]
we need to be able to work with curved polygons and the topology should be preserved after import an export to xtf.

**Comment by m-kuhn** [comment]
@romefi and others, I think you prefer to work without arcs, so it looks like this needs to be an option?

**Comment by pramisters** [comment]
Yes.
Apart from a few exceptions (i.e. AV and datasets that topologically rely on AV) we try to avoid arcs.

**Comment by romefi** [comment]
I'd prefer to work without arcs, never the less there can be situations, where you have to work with arcs. I.e. the canton wants the Zonenplan exactly on the AV-topics including the arcs. So you don't have any choice than to work with arcs. I think an option would make sense with --strokeArcs as default.

**Comment by pramisters** [comment]
I agree with @romefi : Option with --strokeArcs as default.
