### ISSUE TITLE
Option for EPSG-Code

### ISSUE THREAD

**Issue by romefi** [opengisch/projectgenerator#23]
--defaultSrsCode
Without option, EPSG 21781 is set

**Comment by m-kuhn** [comment]
Should be straightforward:

![screenshot from 2017-04-12 09-56-36](https://cloud.githubusercontent.com/assets/588407/24947253/5a9f6532-1f66-11e7-843b-d712969de756.png)

**Comment by m-kuhn** [comment]
Is there some kind of naming convention in the ili filename based on which we can choose a default CRS? 

E.g:

* xyz_LV03.ili
* xyz_LV95.ili
* xyz_EPSG1234.ili

If not, do we have the liberty to introduce that and is it a good idea?

CC @gacarrillor

**Comment by romefi** [comment]
No, there is no convention. Usually the interlis models are for all CRS (e.g. LV03 and LV95) in the same ili-file. So naming the CRS in the filename wouldnt make much sense.
Its more common to mention the CRS in the name of the model (e.g. KbS_LV95_V1_3 in http://models.geo.admin.ch/BAFU/KbS_V1_3.ili), but even that is not a convention.
