### ISSUE TITLE
n-m relations

### ISSUE THREAD

**Issue by romefi** [opengisch/projectgenerator#24]
Check if it is available in ili2pg metadata and then do it

**Comment by m-kuhn** [comment]
Do we have a model to test this with?

**Comment by m-kuhn** [comment]
@romefi @pramisters do we have a model that we can target for a first implementation?

**Comment by pramisters** [comment]
http://models.geo.admin.ch/ARE/Nutzungsplanung_V1_1.ili

It has an n:m-Relation between "Typ" and "Dokument"

`    ASSOCIATION Typ_Dokument =
      Typ -- {0..*} Typ;
      Vorschrift (EXTERNAL) -- {0..*} Nutzungsplanung_LV03_V1_1.Rechtsvorschriften.Dokument;
    END Typ_Dokument;
`

**Comment by m-kuhn** [comment]
Do I have to import something else as well (because `EXTERNAL`)? I cannot see any Vorschrift or Dokument table.

**Comment by m-kuhn** [comment]
Thanks.

Interestingly, there are quite a few foreign keys

```
CREATE TABLE nutzungsflaechen_v1_1.typ_dokument
(
  ...
  typ bigint NOT NULL,
  vorschrift_dokument bigint,
  vorschrift_rechtsvorschrift bigint,
  ...
```

I assume either rechtsvorschrift or dokument needs to be set (but not both)?

**Comment by pramisters** [comment]
Yes, that's correct. Rechtsvorschrift inherits all attributes from dokument (inkl. the assoc. to Typ)
By the way there's another n:m-relation between objects of the class document (ASSOCIATION HinweisWeitereDokumente)

To my knowledge, EXTERNAL in role definitions is only needed when you cross TOPIC borders.

**Comment by m-kuhn** [comment]
Thanks, there are also multiple relations involved in the other one.

```
CREATE TABLE nutzungsflaechen_v1_1.hinweisweiteredokumente
(
  ...
  ursprung_dokument bigint,
  ursprung_rechtsvorschrift bigint,
  hinweis_dokument bigint,
  hinweis_rechtsvorschrift bigint,
```

I guess on the "Ursprung" side you would expect to see two lists, one with "Dokument" and one with "Rechtsvorschrift"?
And on the "Hinweis"-side the same. So in the end, there will be four additional tabs with lists on the Dokument-Form. Can you confirm?

![image](https://user-images.githubusercontent.com/588407/30590488-0eec8550-9d3f-11e7-96a2-9b5c5d76b9cc.png)

**Comment by pramisters** [comment]
Yes, that's correct.
I know this model (as all other models of themes that are part of the ÖREB-Kataster) are rather complex when it comes to relations, but I couldn't  find a simpler federal model with n-m-Relations after a quick search.

**Comment by m-kuhn** [comment]
This will probably need some changes on QGIS side (I think currently we can only make one N:M relation per foreign key to the current table from the network table).

@claeis, is there some information available about the mapping of N:M relations in the ili meta tables?

**Comment by claeis** [comment]
Yes, the n:m tables are listed in T_ILI2DB_TABLE_PROP with ch.ehi.ili2db.tableKind=ASSOCIATION

**Comment by m-kuhn** [comment]
Can the logic be built based on the following assumptions:

* Only n:m tables will be listed with tableKind=ASSOCIATION
* All foreign keys found are thematic relevant, except for the one to t_basket

**Comment by claeis** [comment]
yes
