### ISSUE TITLE
Error opening Generate dialog using Project Generator v3.3.2

### ISSUE THREAD

**Issue by gacarrillor** [opengisch/projectgenerator#256]
There is an error on both Windows 10 and GNU/Linux when opening the Generate dialog using current (from today 2018.10.16) QGIS master. It seems to be while attempting to download models from the repositories.

Project Generator version: 3.3.2

![error_project_generator](https://user-images.githubusercontent.com/652785/47046454-ba708c00-d15a-11e8-9f8b-f17713cabf5f.jpg)

**Comment by pramisters** [comment]
We have the same issue as well on Windows 7, both with Project Generator version 3.3.3 and 3.2.x.
I has been occuring for about a week, both with master and rel-dev.

@m-kuhn: Can I test something?

**Comment by m-kuhn** [comment]
Yes, testing of #257 would be very welcome.
