### ISSUE TITLE
Start crashes with QQGIS 3.4 and 3.5

### ISSUE THREAD

**Issue by romefi** [opengisch/projectgenerator#258]
When starting projectgenerator in QGIS 3.4 or 3.5, I get this error

![image](https://user-images.githubusercontent.com/26796989/47721110-b6129b80-dc4f-11e8-8193-12654c60fb3e.png)

With QGIS 3.3 all works fine.

**Comment by pramisters** [comment]
See #256.
Occured already in a late Version of 3.3.x.

**Comment by m-kuhn** [comment]
Fixed in 3.3.4
