### ISSUE TITLE
I don't understand the semicolon

### ISSUE THREAD

**Issue by wfpinedar** [opengisch/projectgenerator#259]
Hello, sorry, I ask you a question.
why the semicolon in this line https://github.com/opengisch/projectgenerator/blob/1261ade7b108e4e97426294818f651c4f0d81850/projectgenerator/gui/generate_project.py#L84?
thanks and the best day?

**Comment by m-kuhn** [comment]
Probably from a copy paste.
It does not change anything at all to have it or not have it.
