### ISSUE TITLE
PostgreSQL extensions

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/projectgenerator#28]
Most models require `postgis`, some require `uuid-ossp`, there are possibly more. This manual step is a small entry barrier for users which I think would be worth to avoid.

It would IMO be preferable to adjust ili2pg so it creates these extensions automatically when they are required and not present.
(Backup plan: As an alternative we could still parse the ili2pg output for the respective error message and install this in the projectgenerator.)

uuid_generate_v4 : 

     create extension "uuid-ossp";

postgis:

    create extension "postgis";

Opinions?

**Comment by pramisters** [comment]
I fully agree that ili2pg should install at least some extensions if needed.
A common example that I ran into the other day are the UUIDs that are frequently used in the INTERLIS-Models.
If ili2pg detects the code OID AS UUIDOID; in the INTERLIS model it should check if the extension  uuid-ossp is present in PostGIS and install it if it's avalable.

**Comment by m-kuhn** [comment]
CC @claeis, what do you think about this?

**Comment by claeis** [comment]
As a user, I don't like automatism that change the base environment. Because with them, I'm never sure of what software, in what configuration I'm running. 

But as a new option --setuppgext, why not?

**Comment by m-kuhn** [comment]
A new option sounds good for me. :+1:

**Comment by m-kuhn** [comment]
Fixed in 6ee5dcd69ff4
