### ISSUE TITLE
Support proxy for ili2pg

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/projectgenerator#32]
`--proxy` and `--proxyPort` options. Should be retrieved from QgsNetworkAccessManager.

**Comment by m-kuhn** [comment]
@romefi can you share your QGIS proxy settings?

I.e. Is this correct: the chosen proxy type `HttpProxy` and the two fields `host` and `port` filled in?

**Comment by romefi** [comment]
It's either the DefaultProxy (not sure if you can use it for ili2pg), or then its HttpProxy, host, port, user and password. User and password are necessary to get through our proxyserver.

**Comment by m-kuhn** [comment]
I don't find a possibility to specify user / password for ili2pg (https://github.com/claeis/ili2db/blob/master/docs/ili2db.rst only has `--proxy` and `--proxyPort`) Is it me or is this a missing feature?

**Comment by romefi** [comment]
Just realised I don't need an user and password for proxy ili2pg (see https://interlis2.ch/index.php?p=/discussion/69/ili2pg-proxy-mit-login#latest). Important is to avoid the "http://" in the --proxy parameter, then it works.
