### ISSUE TITLE
Choosing the right CRS automatically

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/projectgenerator#33]
Minor issue:

At the moment, it is required to manually set the desired CRS when a ili file is not in 21781 (LV03).

I think it would be nice to automatically (try to) detect the CRS from the model (because it's very easy to miss and can have bad consequences). Some discussion can be found here already: https://github.com/opengisch/projectgenerator/issues/23#issuecomment-293508263.

Proposal:

When a model name is entered which contains `LV03` or `LV95`, the CRS should be automatically chosen. It can still manually be changed by the user if he knows better than the system.
Alternatively we can show a warning shown next to the CRS selector if the current CRS doesn't match the one implied by the model name to make the user aware of a likely mistake.

**Comment by romefi** [comment]
I agree with your proposal. Would be a help if CRS is filled in automatically if the model mention LV03 or LV95. Also a warning if there's a mismatch would be helpful.

**Comment by gacarrillor** [comment]
We don't include the EPSG code nor the CRS name in the ili file name nor in the model name. However, if this proposal is implemented, we could take advantage of it.

**Comment by m-kuhn** [comment]
Is it not possible for ili2pg to already handle this?
As far as I can see, inside the models, datatypes for geometries are either in LV03 or LV95. I wonder if we are effectively fixing this on the wrong level here and it should rather be ili2db taking care of this?

**Comment by m-kuhn** [comment]
CC @claeis

**Comment by romefi** [comment]
I'm not sure if the model defines the explicit CRS in a way that ili2pg can handle without the option --DefaultSrsCode. Claude sure knows.

**Comment by claeis** [comment]
In the projectgenerator you should read the EPSG code from the OGC SF GEOMETRY_COLUMNS/SPATIAL_REF_SYS tables. 

Or do you need to know the ili name of the CRS (=Name of the INTERLIS.METAOBJECT object)?

**Comment by claeis** [comment]
see also claeis/ili2db#87

**Comment by m-kuhn** [comment]
Thanks, claeis/ili2db#87 looks pretty much like what I thought.

The projectgenerator is able to call ili2pg internally, that's where the crs needs to be passed (at the moment).

Later on - for creating the project - the information is read from the database metadata.
