### ISSUE TITLE
JAVA path

### ISSUE THREAD

**Issue by pramisters** [opengisch/projectgenerator#45]
subform for java path selection doesn't open when pressing the button.
Only manual input is possible.

**Comment by pramisters** [comment]
Path selection form works now!
But the automatic search ("standardmässig wird %PATH ... durchsucht") doesn't seem to work, although the JAVA path is present in %PATH.

**Comment by m-kuhn** [comment]
Can you run the following snippet in your python console in QGIS:

```py
from PyQt5.QtCore import QProcess
p = QProcess()
p.start('java')
print(p.exitCode())
```

for me this prints `1`

If I run it for a non-existent command, it prints `255`.

**Comment by pramisters** [comment]
for me this prints  0

**Comment by m-kuhn** [comment]
Can you try it with some non-existent file (e.g. `p.start('jjjjjj')`?

**Comment by pramisters** [comment]
`p.start('gugus')` results in 0 as well

**Comment by m-kuhn** [comment]
What about
`p.start('java.exe')`
and
`p.start('C:/full/path/to/java.exe')`

**Comment by pramisters** [comment]
`p.start('C:\Program Files (x86)\Java\jre1.8.0_144\bin\java.exe')`
results in:
`>>> exec(open(u'C:/Users/KANU/AppData/Local/Temp/tmpcxw7e7ju.py'.encode('utf-8')).read())`
`0`

**Comment by m-kuhn** [comment]
Not a lot of information so far, looks like we need to improve the script a bit

```py
p = QProcess()
p.readyReadStandardOutput.connect(lambda: print('{}: {}'.format(proc, p.readAllStandardOutput())))
p.readyReadStandardError.connect(lambda: print('{}: {}'.format(proc, p.readAllStandardError())))
for proc in ['java', 'java.exe', 'gugus']:
    p.start(proc, ['-version'])
    p.waitForFinished(3000)
    print('{} exited with {}'.format(proc, p.exitCode()))
```

**Comment by m-kuhn** [comment]
@pramisters did you have a chance to run the last test?

**Comment by pramisters** [comment]
java exited with 0
java.exe exited with 0
gugus exited with 0

**Comment by pramisters** [comment]
-----------
java started: False
java exited with 0

-----------
java.exe started: False
java.exe exited with 0

-----------
gugus started: False
gugus exited with 0

**Comment by m-kuhn** [comment]
Thanks
What about the one with the full path annd the environment variable?

**Comment by pramisters** [comment]
I'm not sure what you are referring to.
 p.start('C:\Program Files (x86)\Java\jre1.8.0_144\bin\java.exe') ??
See further up (7.9.17)

**Comment by m-kuhn** [comment]
The script in the comment 3 up should also include

```
import os
print('Path: {}'.format(os.environ['PATH']))
```

and produce an output for the full path

```
for proc in ['C:/Program Files (x86)/Java/jre1.8.0_144/bin/java.exe', 'java', 'java.exe', 'gugus']:
```

I couldn't find these two outputs in your response
