### ISSUE TITLE
Range constraints aren't set in form widget

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/projectgenerator#53]
ili2pg imports range constraints, e.g. in the form of:

 vonkm numeric(9,3) NOT NULL, -- @iliname vonKM
 CONSTRAINT gewaesserabschnitt_vonkm_check CHECK (vonkm >= '-100.0'::numeric AND vonkm <= 100000.0),

Project generator does not yet translate that to QGIS client-side constraints. It would be useful to have such check constraints on the client as well.

QGIS sets a unreasonably high value as min max:

Min: -179769000000000006323030492138942643493033036433685336215410983289126434148906289940615299632196609445533816320312774433484859900046491141051651091672734470972759941382582304802812882753059262973637182942535982636884444611376868582636745405553206881859340916340092953230149901406738427651121855107737424232448.00

Max:
179769000000000006323030492138942643493033036433685336215410983289126434148906289940615299632196609445533816320312774433484859900046491141051651091672734470972759941382582304802812882753059262973637182942535982636884444611376868582636745405553206881859340916340092953230149901406738427651121855107737424232448.00

**Comment by m-kuhn** [comment]
With the current version of QGIS/Projectgenerator this works as expected (checked abfallsammelstelle.orientierung) is this still an issue, @andreasneumann ?

**Comment by gacarrillor** [comment]
Confirmed. The regular expression used in Project Generator doesn't match such syntax yet:
`CHECK (vonkm >= '-100.0'::numeric AND vonkm <= 100000.0)`

**Comment by gacarrillor** [comment]
Fixed by PR #112.
