### ISSUE TITLE
Table and column display names

### ISSUE THREAD

**Issue by gacarrillor** [opengisch/projectgenerator#62]
As of [July 6](https://github.com/claeis/ili2db/commits/master), ili2pg supports a meta-attribute called `@ili2db.dispName` to set table and column display names (i.e., aliases). I've basically added support for such meta-attribute to make it easier for Project Generator to extract aliases.
 
Now, I would like to know your opinion on: 

1. Making Project Generator aware of such aliases from the database (namely, from ili2db metadata tables), and
2. Closing issues #48 and #52 in favor of this one? 

cc @andreasneumann

**Comment by m-kuhn** [comment]
@gacarrillor that would be much appreciated. Are there any downsides of doing this?

**Comment by andreasneumann** [comment]
@gacarrillor - where does ili2db.dispName come from? Is it taken from the model from comments?
Do you have an example how such a model looks like? Is there a special markup in the comment that has to be used?

**Comment by gacarrillor** [comment]
@andreasneumann, `@ili2db.dispName` is being used already for [Enum element names](https://github.com/opengisch/projectgenerator/issues/47#issuecomment-312367423). Instead of writing generic comments (ilidocs), one can set meta-attributes to define specific data about model objects. For instance, a meta-attribute is [planned for EPSG codes](https://github.com/claeis/ili2db/issues/87).

Regarding tables/columns, the syntax is as follows:

```
    !!@ili2db.dispName="Documento de Ordenamiento Territorial"
    CLASS DocumentoOT =
      !!@ili2db.dispName="Tipo de documento de Ordenamiento Territorial"
      /** 
        Other comments for 'tipo' attribute
      */
      tipo : MANDATORY documentoOTTipo;
      descripcion : MTEXT;
    END DocumentoOT; 
```
`!!@ili2db.dispName` is transferred into [recently added](https://github.com/claeis/ili2db/blob/master/docs/CHANGELOG.txt#L28) meta-data tables (that you need to enable with `--createMetaInfo` option when importing the schema) `t_ili2db_table_prop` and `t_ili2db_column_prop`. For the example above, the table display name would be stored in this way:

```
 tablename  |         tag            |         setting
---------------------------------------------------------------------------
documentoot | ch.ehi.ili2db.dispName | Documento de Ordenamiento Territorial
```


Finally, `@ili2db.dispName` also works for structures.
