### ISSUE TITLE
Import configuration: no special characters allowed

### ISSUE THREAD

**Issue by zigertiger** [opengisch/projectgenerator#66]
At the import of either an INTERLIS model definition or an existing PostGIS schema, no special characters can used in the configuration dialogues.

Special characters like "-", "." must be useable in the configuration dialogue. 

E.g. host, username: srv-gis-01, peter.staub

**Comment by gacarrillor** [comment]
@m-kuhn This issue is solved already in [branch: exportV2](https://github.com/opengisch/projectgenerator/tree/exportV2).

**Comment by m-kuhn** [comment]
@gacarrillor that's in master now. Can you tell me when you have translated the new text also to Spanish then I will tag it for release.

**Comment by m-kuhn** [comment]
Fixed in 0.6.0
