### ISSUE TITLE
Map extent from INTERLIS models

### ISSUE THREAD

**Issue by gacarrillor** [opengisch/projectgenerator#83]
Since INTERLIS models have coordinate ranges that play a role when validating data (i.e., avoiding data export when features are outside of it), couldn't we read the allowed extent and do things like the following?

 + Set initial map extent 
 + Create a spatial bookmark called "Allowed extent" (and open the Spatial Boormarks Panel each time a project is generated)
 + Show a warning message when saving features out of the allowed extent

**Comment by m-kuhn** [comment]
Absolutely.
Is this in the DB already?

**Comment by gacarrillor** [comment]
As far as I know, it is not there. I'm afraid we would need to parse the ili models. 

BTW, what of the three suggestions would you like to have in Project Generator? All 3 :)? Can you envision another way to make the project aware of allowed extents?

**Comment by m-kuhn** [comment]
> As far as I know, it is not there. I'm afraid we would need to parse the ili models.

We always wanted to avoid that, not only because we do not always have a local ili file (repository) and well... there is already a parser written in Java...
Maybe @claeis know something about the availability of extents in the database?

> BTW, what of the three suggestions would you like to have in Project Generator? All 3 :)? Can you envision another way to make the project aware of allowed extents?

Yes, all 3 of them sound good, the first two are probably easiest. Maybe additionally it can be added to the project expression variables so it can be used wherever one wants?

**Comment by gacarrillor** [comment]
Hi @m-kuhn!

We (@Alelizzt and I) have worked on this and have some findings/questions. Namely, 

+ We have set the map extent to the extent set in the INTERLIS model.
+ A spatial bookmark cannot be created because such class is not exposed in the API yet (it's in qgisapp.cpp).
+ As a way to indicate the region where users are allowed to add features, we have created a rubber band and added it to the canvas. Here we have a question: could the "New Project" button remove all map items (like rubber bands) from the map? As is, we have no easy way to let the user remove the rubber band we create :( 

What do you think about it?

**Comment by gacarrillor** [comment]
> The rubberband will only be shown once upon creation and then no longer on subsequent loadings of the project? Is this what's expected? All the other things that are done are "generated in the project", hence the name ;)

So, you don't see a way of storing the rubber band into the project? 

> Would it work to use QgsProject.instance().writeEntry() etc. instead to generate the bookmarks. It's not the sexiest API, but it gets saved to the project.

I guess it would. We will give this a try.

> Nice, can you make a PR with that one?

Sure, but I feel it still incomplete. We will add at least the bookmark before the PR.

By the way, I've read your QEP regarding validations on editing time. Will (or could) it include a way to set an edits-allowed extent to limit the region where edits can take place?

**Comment by m-kuhn** [comment]
> So, you don't see a way of storing the rubber band into the project?

At least not a way that it will work without additional code to make it re-appear.

> Sure, but I feel it still incomplete. We will add at least the bookmark before the PR.

Adding bookmarks sounds good. Anything more is best served in a different PR.

> By the way, I've read your QEP regarding validations on editing time. Will (or could) it include a way to set an edits-allowed extent to limit the region where edits can take place?

I guess yes, but probably not for 3.4 ;)
