### ISSUE TITLE
Show ili2pg options in settings->about

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/projectgenerator#93]
create text automatically if somehow possible

**Comment by pramisters** [comment]
In case of "Schema Import" the option "--smart1Inheritance" must not be listed as it could also be set to "--smart2Inheritance" in "Advanced Options" if you choose "Generate" and INTERLIS as a source.

![projectgen_ili2db_options](https://user-images.githubusercontent.com/23503534/39477788-ddec5d1a-4d4f-11e8-8388-f8be9a1fa23d.png)

**Comment by pramisters** [comment]
No, currently the displayed options are not correct for Data Import (too many listed options)
The way I see it, the display of the used options are  mainly relevant for the Schema import.

Is your 1st proposal something like:

--smart1Inheritance (see Advanced Options)
OR
--smart2Inheritance (see Advanced Options)

How does the user find the Advanced Options dialog when he is in the Settings dialog?

What about moving the Advanced Options dialog (from Generate Project based on INTERLIS) to  the new Settings Dialog? Is that what you mean with your 2nd proposal?

**Comment by m-kuhn** [comment]
> No, currently the displayed options are not correct for Data Import (too many listed options)

Also others (apart from inheritance)?

> How does the user find the Advanced Options dialog when he is in the Settings dialog?
> 
> What about moving the Advanced Options dialog (from Generate Project based on INTERLIS) to the new Settings Dialog? Is that what you mean with your 2nd proposal?

For me it would also work fine to configure the inheritance schema on system level (in the settings) and not on import level. @gacarrillor you introduced this option, what's your opinion?

**Comment by pramisters** [comment]
Just to many options  for Data Import. Most of the displayed options are only relevant for the preceding Schema Import.

--smart2Inheritance was commissioned by us (Kt. ZG).  We always use that option.

That's why I stumbled across the display of --smart1Inheritance and was worried that --smart2Inheritance was cancelled as an option in the Project Generator. But luckily it's not.

**Comment by m-kuhn** [comment]
@zigertiger, what was your preferred inheritance approach?

**Comment by zigertiger** [comment]
**smart1** since that produces (normally) fewer tables

**Comment by pramisters** [comment]
The question is only: Where to put the option in the GUI

**Comment by m-kuhn** [comment]
Let's move it to app-wide settings in this case.
@gacarrillor will you take care of that?

> Just too many options for Data Import. Most of the displayed options are only relevant for the preceding Schema Import.

I thought that this can be done in a single step too, so specifying or not specifying them are both waranted. What's shown there is what is used by projectgenerator currently and so far I think we haven't had any reports about bad side-effects by these options.

**Comment by gacarrillor** [comment]
@m-kuhn  I'll do it!

> I thought that this can be done in a single step too, so specifying or not specifying them are both waranted. What's shown there is what is used by projectgenerator currently and so far I think we haven't had any reports about bad side-effects by these options.

It can be done in a single step, but as far as I understand, it's not the desired behaviour. See https://github.com/claeis/ili2db/issues/112 So, it would make sense to remove `schemaImport` specific parameters from a data `import` command.
