### ISSUE TITLE
Embedded domains in classes

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/projectgenerator#96]
The value relation widget is not properly configured and populated for embedded classes as in the following example.

https://github.com/opengisch/projectgenerator/blob/master/projectgenerator/tests/testdata/ilimodels/ZG_Abfallsammelstellen_ZEBA_V1.ili#L71-L74

Ili2pg doesn't create foreign key constraints.

**Comment by claeis** [comment]
depends on claeis/ili2db#19
