### ISSUE TITLE
Enumerations are not working

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/projectgenerator#97]
Domains referenced in abstract base classes are not properly configured as relation reference widgets.

See e.g.
https://github.com/opengisch/projectgenerator/blob/master/projectgenerator/tests/testdata/ilimodels/ZG_Abfallsammelstellen_ZEBA_V1.ili#L108
https://github.com/opengisch/projectgenerator/blob/master/projectgenerator/tests/testdata/ilimodels/ZG_Abfallsammelstellen_ZEBA_V1.ili#L53-L60

Ili2pg does not create foreign keys

**Comment by claeis** [comment]
Problem is not the abstract base class and/or domain reference, but the enumeration.
Depends on claeis/ili2db#19

**Comment by gacarrillor** [comment]
By @m-kuhn
> One issue discovered in a quick check: relations are initialized with ilicode while the field name is iliCode (at least for domains, created a model from the repository: KbS_LV95_V1_3, add feature belasteter standort -> choose standaorttyp, not working).

I'll have a look at this. As far as I know, the field gets the name `ilicode` in PG.

**Comment by gacarrillor** [comment]
By @m-kuhn 
> I assume this is a broader issue with capitalization of attribute names in gpkg, rather than something isolated to domain-class-relations, no?

Actually, testing the model you mention (`KbS_LV95_V1_3`) I can get the domain-class relation correctly configured using GeoPackage. With PostGIS, it is correctly configured for the point layer `belasteter_standort`, but strangely not for the polygon layer `belasteter_standort`.

In both DBMSs, the field is created in lowercase in the DB, but unlike PostGIS, GeoPackage doesn't seem to store the field comment (which is set as field alias by Project Generator when working with PostGIS).

**Comment by claeis** [comment]
Not really related to this issue, but to the comments: ili2db generates sql statements that use unquoted sql names. How unquoted sql names are compared by the db, is db product dependent. 

- In PG,  unquoted names are always folded to lower case. 
- Sqlite is case-insensitive. 
- Oracle changes unquoted identifiers to uppercase. 
- Mssql: depends on the default collation of the database.

**Comment by m-kuhn** [comment]
In QGIS field name matching is normally done case-sensitive whenever the configuration comes from a place where the field name can be trusted (as in "select a field from a list from available fields on a combobox") - this rule applies here.

When it's used within an expression, the same is tried first and, if unsuccessful, another try is made case-insensitive and based on the attribute alias.

Once a field is identified to match one on the database, queries are sent within the query with quoted identifiers (for at least pg and gpkg) but always with capitalization as found at load time on the db.

**Comment by gacarrillor** [comment]
By @m-kuhn:

> One issue discovered in a quick check: relations are initialized with ilicode while the field name is iliCode (at least for domains, created a model from the repository: KbS_LV95_V1_3, add feature belasteter standort -> choose standaorttyp, not working).

This is rather a broader issue with relations and tables with multiple geometry attributes. Just opened #116 to separate concerns.

**Comment by m-kuhn** [comment]
Thanks for the investigation.
Strange that #116 affects capitalization of already detected attributes, so with other models with only one geometry per table it works?

**Comment by gacarrillor** [comment]
Not sure what you mean about capitalization. 
As far as we've tested, yes, it works.

**Comment by m-kuhn** [comment]
> relations are initialized with ilicode while the field name is iliCode

Compare `ilicode` to `iliCode`, when replacing this in the .qgs file created with the gpkg branch, things were fixed

**Comment by gacarrillor** [comment]
In that case, I think it deserves its own issue. Could you please open it?
I could then test things like if it's introduced by the GeoPackage branch.

**Comment by gacarrillor** [comment]
The original issue (enumeration "Abfallart" from abstract class not being configured) was fixed by PR #112. Moreover, unit tests (using the same mentioned models) were added.
